### ISSUE TITLE
Name of ended auction is not displayed

### ISSUE THREAD

**Issue by matthias-luger** [Ekwav/HypixelSkyblock#5]
The endedAuction command has sometimes the itemName property not filled

**Comment by Ekwav** [comment]
This was worked around with https://github.com/Ekwav/HypixelSkyblock/commit/bf07934d424b236d3a81f86758a1f8eaf28a798a#diff-75c77118c3a53a0fee501e23f6caad6208c9e36fc6d002cde56e4152d5b21998
